In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
import os

print("Files available in Colab:")
for file in os.listdir('/content'):
    print(file)

Files available in Colab:
.config
patients.csv
admissions.csv
treatments.csv
doctors.csv
vitals.csv
sample_data

In [ ]:
# Load healthcare datasets

patients = pd.read_csv('/content/patients.csv')
admissions = pd.read_csv('/content/admissions.csv')
doctors = pd.read_csv('/content/doctors.csv')
treatments = pd.read_csv('/content/treatments.csv')
vitals = pd.read_csv('/content/vitals.csv')

print("Datasets loaded successfully.\n")

print("Patients   :", patients.shape)
print("Admissions :", admissions.shape)
print("Doctors    :", doctors.shape)
print("Treatments :", treatments.shape)
print("Vitals     :", vitals.shape)

Datasets loaded successfully.

Patients   : (1690, 8)
Admissions : (3324, 7)
Doctors    : (40, 5)
Treatments : (8329, 6)
Vitals     : (33148, 7)

In [ ]:
# Display structure of all datasets

datasets = {
    "Patients": patients,
    "Admissions": admissions,
    "Doctors": doctors,
    "Treatments": treatments,
    "Vitals": vitals
}

for name, df in datasets.items():
    print("=" * 70)
    print(f"{name} Dataset")
    print("=" * 70)
    print("Columns:")
    print(df.columns.tolist())
    print("\nData Types:")
    print(df.dtypes)
    print()

======================================================================
Patients Dataset
======================================================================
Columns:
['patient_id', 'first_name', 'last_name', 'dob', 'gender', 'contact_no', 'address', 'chronic_conditions']

Data Types:
patient_id             int64
first_name            object
last_name             object
dob                   object
gender                object
contact_no             int64
address               object
chronic_conditions    object
dtype: object

======================================================================
Admissions Dataset
======================================================================
Columns:
['admission_id', 'patient_id', 'admission_date', 'discharge_date', 'diagnosis', 'doctor_id', 'room_no']

Data Types:
admission_id       int64
patient_id         int64
admission_date    object
discharge_date    object
diagnosis         object
doctor_id          int64
room_no           object
dtype: object

======================================================================
Doctors Dataset
======================================================================
Columns:
['doctor_id', 'first_name', 'last_name', 'specialization', 'contact_no']

Data Types:
doctor_id          int64
first_name        object
last_name         object
specialization    object
contact_no         int64
dtype: object

======================================================================
Treatments Dataset
======================================================================
Columns:
['treatment_id', 'admission_id', 'treatment_date', 'procedure', 'medication', 'dosage']

Data Types:
treatment_id       int64
admission_id       int64
treatment_date    object
procedure         object
medication        object
dosage            object
dtype: object

======================================================================
Vitals Dataset
======================================================================
Columns:
['vital_id', 'admission_id', 'recorded_time', 'heart_rate', 'blood_pressure', 'oxygen_level', 'temperature']

Data Types:
vital_id            int64
admission_id        int64
recorded_time      object
heart_rate          int64
blood_pressure     object
oxygen_level        int64
temperature       float64
dtype: object

In [ ]:
# Check missing values in all datasets

for name, df in datasets.items():
    print("=" * 70)
    print(f"{name} - Missing Values")
    print("=" * 70)

    missing = df.isnull().sum()
    missing_percent = (df.isnull().sum() / len(df) * 100).round(2)

    missing_summary = pd.DataFrame({
        'Missing_Count': missing,
        'Missing_Percentage': missing_percent
    })

    print(missing_summary)
    print()

======================================================================
Patients - Missing Values
======================================================================
                    Missing_Count  Missing_Percentage
patient_id                      0                 0.0
first_name                      0                 0.0
last_name                       0                 0.0
dob                             0                 0.0
gender                          0                 0.0
contact_no                      0                 0.0
address                         0                 0.0
chronic_conditions            240                14.2

======================================================================
Admissions - Missing Values
======================================================================
                Missing_Count  Missing_Percentage
admission_id                0                 0.0
patient_id                  0                 0.0
admission_date              0                 0.0
discharge_date              0                 0.0
diagnosis                   0                 0.0
doctor_id                   0                 0.0
room_no                     0                 0.0

======================================================================
Doctors - Missing Values
======================================================================
                Missing_Count  Missing_Percentage
doctor_id                   0                 0.0
first_name                  0                 0.0
last_name                   0                 0.0
specialization              0                 0.0
contact_no                  0                 0.0

======================================================================
Treatments - Missing Values
======================================================================
                Missing_Count  Missing_Percentage
treatment_id                0                 0.0
admission_id                0                 0.0
treatment_date              0                 0.0
procedure                   0                 0.0
medication                  0                 0.0
dosage                      0                 0.0

======================================================================
Vitals - Missing Values
======================================================================
                Missing_Count  Missing_Percentage
vital_id                    0                 0.0
admission_id                0                 0.0
recorded_time               0                 0.0
heart_rate                  0                 0.0
blood_pressure              0                 0.0
oxygen_level                0                 0.0
temperature                 0                 0.0

In [ ]:
# Check duplicate records and primary key duplicates

primary_keys = {
    "Patients": "patient_id",
    "Admissions": "admission_id",
    "Doctors": "doctor_id",
    "Treatments": "treatment_id",
    "Vitals": "vital_id"
}

for name, df in datasets.items():
    pk = primary_keys[name]

    print("=" * 70)
    print(f"{name}")
    print("=" * 70)
    print(f"Full duplicate rows      : {df.duplicated().sum()}")
    print(f"Duplicate {pk} values    : {df[pk].duplicated().sum()}")
    print(f"Unique {pk} values       : {df[pk].nunique()}")
    print(f"Total rows               : {len(df)}")
    print()

======================================================================
Patients
======================================================================
Full duplicate rows      : 0
Duplicate patient_id values    : 0
Unique patient_id values       : 1690
Total rows               : 1690

======================================================================
Admissions
======================================================================
Full duplicate rows      : 0
Duplicate admission_id values    : 0
Unique admission_id values       : 3324
Total rows               : 3324

======================================================================
Doctors
======================================================================
Full duplicate rows      : 0
Duplicate doctor_id values    : 0
Unique doctor_id values       : 40
Total rows               : 40

======================================================================
Treatments
======================================================================
Full duplicate rows      : 0
Duplicate treatment_id values    : 0
Unique treatment_id values       : 8329
Total rows               : 8329

======================================================================
Vitals
======================================================================
Full duplicate rows      : 0
Duplicate vital_id values    : 0
Unique vital_id values       : 33148
Total rows               : 33148

In [ ]:
# Foreign Key Validation

print("=" * 70)
print("FOREIGN KEY VALIDATION")
print("=" * 70)

# Admissions → Patients
invalid_patient_fk = ~admissions['patient_id'].isin(patients['patient_id'])
print(f"\nAdmissions → Patients")
print(f"Invalid patient_id references: {invalid_patient_fk.sum()}")

# Admissions → Doctors
invalid_doctor_fk = ~admissions['doctor_id'].isin(doctors['doctor_id'])
print(f"\nAdmissions → Doctors")
print(f"Invalid doctor_id references: {invalid_doctor_fk.sum()}")

# Vitals → Admissions
invalid_vitals_fk = ~vitals['admission_id'].isin(admissions['admission_id'])
print(f"\nVitals → Admissions")
print(f"Invalid admission_id references: {invalid_vitals_fk.sum()}")

# Treatments → Admissions
invalid_treatments_fk = ~treatments['admission_id'].isin(admissions['admission_id'])
print(f"\nTreatments → Admissions")
print(f"Invalid admission_id references: {invalid_treatments_fk.sum()}")

print("\nForeign key validation completed.")

======================================================================
FOREIGN KEY VALIDATION
======================================================================

Admissions → Patients
Invalid patient_id references: 0

Admissions → Doctors
Invalid doctor_id references: 0

Vitals → Admissions
Invalid admission_id references: 0

Treatments → Admissions
Invalid admission_id references: 0

Foreign key validation completed.

In [ ]:
# Convert date and datetime columns

patients['dob'] = pd.to_datetime(patients['dob'])

admissions['admission_date'] = pd.to_datetime(admissions['admission_date'])
admissions['discharge_date'] = pd.to_datetime(admissions['discharge_date'])

treatments['treatment_date'] = pd.to_datetime(treatments['treatment_date'])

vitals['recorded_time'] = pd.to_datetime(vitals['recorded_time'])

print("Date and datetime columns converted successfully.\n")

print("Patients dob:", patients['dob'].dtype)
print("Admissions admission_date:", admissions['admission_date'].dtype)
print("Admissions discharge_date:", admissions['discharge_date'].dtype)
print("Treatments treatment_date:", treatments['treatment_date'].dtype)
print("Vitals recorded_time:", vitals['recorded_time'].dtype)

Date and datetime columns converted successfully.

Patients dob: datetime64[ns]
Admissions admission_date: datetime64[ns]
Admissions discharge_date: datetime64[ns]
Treatments treatment_date: datetime64[ns]
Vitals recorded_time: datetime64[ns]

In [ ]:
# Validate admission and discharge dates

admissions['length_of_stay'] = (
    admissions['discharge_date'] - admissions['admission_date']
).dt.days

print("=" * 70)
print("ADMISSION DATE VALIDATION")
print("=" * 70)

print("\nInvalid admission periods (discharge before admission):")
print((admissions['length_of_stay'] < 0).sum())

print("\nLength of Stay Summary:")
print(admissions['length_of_stay'].describe())

print("\nMinimum Length of Stay:", admissions['length_of_stay'].min(), "days")
print("Maximum Length of Stay:", admissions['length_of_stay'].max(), "days")
print("Average Length of Stay:", round(admissions['length_of_stay'].mean(), 2), "days")

======================================================================
ADMISSION DATE VALIDATION
======================================================================

Invalid admission periods (discharge before admission):
0

Length of Stay Summary:
count    3324.000000
mean        5.966907
std         2.575514
min         2.000000
25%         4.000000
50%         6.000000
75%         8.000000
max        10.000000
Name: length_of_stay, dtype: float64

Minimum Length of Stay: 2 days
Maximum Length of Stay: 10 days
Average Length of Stay: 5.97 days

In [ ]:
# Validate treatment dates against admission and discharge dates

treatment_check = treatments.merge(
    admissions[['admission_id', 'admission_date', 'discharge_date']],
    on='admission_id',
    how='left'
)

before_admission = (
    treatment_check['treatment_date'] < treatment_check['admission_date']
).sum()

after_discharge = (
    treatment_check['treatment_date'] > treatment_check['discharge_date']
).sum()

print("=" * 70)
print("TREATMENT DATE VALIDATION")
print("=" * 70)

print("\nTreatments before admission:", before_admission)
print("Treatments after discharge :", after_discharge)

print("\nTreatment date range:")
print("Minimum:", treatments['treatment_date'].min())
print("Maximum:", treatments['treatment_date'].max())

======================================================================
TREATMENT DATE VALIDATION
======================================================================

Treatments before admission: 4243
Treatments after discharge : 3925

Treatment date range:
Minimum: 2025-03-11 00:00:00
Maximum: 2026-03-11 00:00:00

In [ ]:
# Validate vital-record dates against admission and discharge dates

vitals_check = vitals.merge(
    admissions[['admission_id', 'admission_date', 'discharge_date']],
    on='admission_id',
    how='left'
)

vitals_before_admission = (
    vitals_check['recorded_time'].dt.date <
    vitals_check['admission_date'].dt.date
).sum()

vitals_after_discharge = (
    vitals_check['recorded_time'].dt.date >
    vitals_check['discharge_date'].dt.date
).sum()

print("=" * 70)
print("VITALS DATE VALIDATION")
print("=" * 70)

print("\nVitals before admission:", vitals_before_admission)
print("Vitals after discharge :", vitals_after_discharge)

print("\nVitals recording date range:")
print("Minimum:", vitals['recorded_time'].min())
print("Maximum:", vitals['recorded_time'].max())

======================================================================
VITALS DATE VALIDATION
======================================================================

Vitals before admission: 3437
Vitals after discharge : 29064

Vitals recording date range:
Minimum: 2026-01-01 00:02:17
Maximum: 2026-03-12 10:43:23

In [ ]:
# Validate vital sign ranges

print("=" * 70)
print("VITAL SIGN VALIDATION")
print("=" * 70)

print("\nHeart Rate:")
print("Minimum:", vitals['heart_rate'].min())
print("Maximum:", vitals['heart_rate'].max())

print("\nOxygen Level:")
print("Minimum:", vitals['oxygen_level'].min())
print("Maximum:", vitals['oxygen_level'].max())

print("\nTemperature:")
print("Minimum:", vitals['temperature'].min())
print("Maximum:", vitals['temperature'].max())

print("\nBlood Pressure - Sample Values:")
print(vitals['blood_pressure'].value_counts().head(10))

======================================================================
VITAL SIGN VALIDATION
======================================================================

Heart Rate:
Minimum: 60
Maximum: 120

Oxygen Level:
Minimum: 88
Maximum: 100

Temperature:
Minimum: 97.0
Maximum: 101.0

Blood Pressure - Sample Values:
blood_pressure
123/80    50
142/89    49
138/85    49
115/70    48
139/78    47
141/77    47
121/94    46
133/95    46
130/70    46
145/72    46
Name: count, dtype: int64

In [ ]:
# Split blood pressure into systolic and diastolic values

vitals[['systolic_bp', 'diastolic_bp']] = (
    vitals['blood_pressure']
    .str.split('/', expand=True)
    .astype(int)
)

print("=" * 70)
print("BLOOD PRESSURE VALIDATION")
print("=" * 70)

print("\nSystolic BP:")
print("Minimum:", vitals['systolic_bp'].min())
print("Maximum:", vitals['systolic_bp'].max())

print("\nDiastolic BP:")
print("Minimum:", vitals['diastolic_bp'].min())
print("Maximum:", vitals['diastolic_bp'].max())

print("\nMissing parsed values:")
print(vitals[['systolic_bp', 'diastolic_bp']].isnull().sum())

======================================================================
BLOOD PRESSURE VALIDATION
======================================================================

Systolic BP:
Minimum: 110
Maximum: 150

Diastolic BP:
Minimum: 70
Maximum: 95

Missing parsed values:
systolic_bp     0
diastolic_bp    0
dtype: int64

In [ ]:
# Check categorical values

print("=" * 70)
print("CATEGORICAL VALUE VALIDATION")
print("=" * 70)

print("\n--- Patient Gender ---")
print(patients['gender'].value_counts(dropna=False))

print("\n--- Chronic Conditions ---")
print(patients['chronic_conditions'].value_counts(dropna=False).head(15))

print("\n--- Admission Diagnoses ---")
print(admissions['diagnosis'].value_counts(dropna=False))

print("\n--- Doctor Specializations ---")
print(doctors['specialization'].value_counts(dropna=False))

print("\n--- Treatment Procedures ---")
print(treatments['procedure'].value_counts(dropna=False).head(15))

print("\n--- Treatment Medications ---")
print(treatments['medication'].value_counts(dropna=False).head(15))

======================================================================
CATEGORICAL VALUE VALIDATION
======================================================================

--- Patient Gender ---
gender
Female    886
Male      804
Name: count, dtype: int64

--- Chronic Conditions ---
chronic_conditions
Heart Disease     254
Kidney Disease    253
Asthma            251
NaN               240
Diabetes          236
Hypertension      233
COPD              223
Name: count, dtype: int64

--- Admission Diagnoses ---
diagnosis
Hypertension             746
Respiratory Infection    689
Chest Pain               485
Heart Failure            473
Pneumonia                454
Asthma Attack            252
Diabetes Complication    225
Name: count, dtype: int64

--- Doctor Specializations ---
specialization
Neurologist          12
Cardiologist         11
Pulmonologist         8
Endocrinologist       5
General Physician     4
Name: count, dtype: int64

--- Treatment Procedures ---
procedure
Oxygen Therapy               2905
ECG Monitoring               2390
Blood Pressure Monitoring    1871
Nebulization                  617
IV Fluid Therapy              546
Name: count, dtype: int64

--- Treatment Medications ---
medication
Amoxicillin     2905
Aspirin         2390
Metoprolol      1871
Salbutamol       617
Atorvastatin     546
Name: count, dtype: int64

In [ ]:
# Handle missing chronic condition values

patients['chronic_conditions'] = patients['chronic_conditions'].fillna(
    'No Recorded Condition'
)

print("=" * 70)
print("MISSING VALUE HANDLING")
print("=" * 70)

print("\nMissing values after cleaning:")
print(patients['chronic_conditions'].isnull().sum())

print("\nUpdated Chronic Conditions:")
print(patients['chronic_conditions'].value_counts())

======================================================================
MISSING VALUE HANDLING
======================================================================

Missing values after cleaning:
0

Updated Chronic Conditions:
chronic_conditions
Heart Disease            254
Kidney Disease           253
Asthma                   251
No Recorded Condition    240
Diabetes                 236
Hypertension             233
COPD                     223
Name: count, dtype: int64

In [ ]:
# Calculate patient age

reference_date = admissions['admission_date'].max()

patients['age'] = (
    (reference_date - patients['dob']).dt.days / 365.25
).astype(int)

print("=" * 70)
print("PATIENT AGE VALIDATION")
print("=" * 70)

print("\nMinimum Age:", patients['age'].min())
print("Maximum Age:", patients['age'].max())
print("Average Age:", round(patients['age'].mean(), 2))

print("\nAge Summary:")
print(patients['age'].describe())

======================================================================
PATIENT AGE VALIDATION
======================================================================

Minimum Age: 18
Maximum Age: 90
Average Age: 55.02

Age Summary:
count    1690.000000
mean       55.023669
std        21.189006
min        18.000000
25%        37.000000
50%        56.000000
75%        73.000000
max        90.000000
Name: age, dtype: float64

In [ ]:
# Create admission-level features

admissions = admissions.sort_values(
    ['patient_id', 'admission_date']
).copy()

admissions['previous_admissions'] = (
    admissions.groupby('patient_id').cumcount()
)

print("=" * 70)
print("ADMISSION-LEVEL FEATURES")
print("=" * 70)

print("\nPrevious Admissions Summary:")
print(admissions['previous_admissions'].describe())

print("\nSample:")
print(
    admissions[
        ['admission_id', 'patient_id', 'admission_date',
         'length_of_stay', 'previous_admissions']
    ].head(10)
)

======================================================================
ADMISSION-LEVEL FEATURES
======================================================================

Previous Admissions Summary:
count    3324.000000
mean        0.649819
std         0.737702
min         0.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         2.000000
Name: previous_admissions, dtype: float64

Sample:
   admission_id  patient_id admission_date  length_of_stay  \
0          2001        1001     2026-02-07               6
1          2002        1001     2026-03-07              10
2          2003        1002     2025-05-16               5
4          2005        1003     2025-08-11              10
3          2004        1003     2025-12-08               2
5          2006        1004     2025-03-11               8
6          2007        1004     2025-07-15              10
7          2008        1004     2025-09-10               7
8          2009        1005     2025-04-13               4
9          2010        1006     2025-03-28               8

   previous_admissions
0                    0
1                    1
2                    0
4                    0
3                    1
5                    0
6                    1
7                    2
8                    0
9                    0

In [ ]:
# Create chronic condition indicator

patients['has_chronic_condition'] = (
    patients['chronic_conditions'] != 'No Recorded Condition'
).astype(int)

print("=" * 70)
print("CHRONIC CONDITION FEATURE")
print("=" * 70)

print("\nPatients with chronic conditions:")
print(patients['has_chronic_condition'].sum())

print("\nPatients without recorded chronic conditions:")
print((patients['has_chronic_condition'] == 0).sum())

print("\nFeature distribution:")
print(patients['has_chronic_condition'].value_counts())

======================================================================
CHRONIC CONDITION FEATURE
======================================================================

Patients with chronic conditions:
1450

Patients without recorded chronic conditions:
240

Feature distribution:
has_chronic_condition
1    1450
0     240
Name: count, dtype: int64

In [ ]:
# Aggregate vital signs at admission level

vitals_agg = (
    vitals.groupby('admission_id')
    .agg(
        avg_heart_rate=('heart_rate', 'mean'),
        min_heart_rate=('heart_rate', 'min'),
        max_heart_rate=('heart_rate', 'max'),
        avg_oxygen_level=('oxygen_level', 'mean'),
        min_oxygen_level=('oxygen_level', 'min'),
        avg_temperature=('temperature', 'mean'),
        max_temperature=('temperature', 'max'),
        avg_systolic_bp=('systolic_bp', 'mean'),
        avg_diastolic_bp=('diastolic_bp', 'mean'),
        vital_readings=('vital_id', 'count')
    )
    .reset_index()
)

print("=" * 70)
print("VITALS AGGREGATION")
print("=" * 70)

print("\nAggregated shape:", vitals_agg.shape)

print("\nSample:")
print(vitals_agg.head())

print("\nMissing values:")
print(vitals_agg.isnull().sum())

======================================================================
VITALS AGGREGATION
======================================================================

Aggregated shape: (3324, 11)

Sample:
   admission_id  avg_heart_rate  min_heart_rate  max_heart_rate  \
0          2001       91.000000              65             120
1          2002       90.916667              67             117
2          2003       83.866667              61             118
3          2004       83.777778              60             114
4          2005       90.400000              66             114

   avg_oxygen_level  min_oxygen_level  avg_temperature  max_temperature  \
0         93.888889                88        99.253333           100.48
1         92.666667                88        99.038333           100.85
2         94.200000                88        98.618667           100.41
3         92.222222                88        98.910000           100.60
4         95.000000                89        99.197000           100.86

   avg_systolic_bp  avg_diastolic_bp  vital_readings
0       129.444444         83.000000               9
1       119.916667         84.583333              12
2       133.333333         82.133333              15
3       139.555556         79.555556               9
4       134.100000         81.500000              10

Missing values:
admission_id        0
avg_heart_rate      0
min_heart_rate      0
max_heart_rate      0
avg_oxygen_level    0
min_oxygen_level    0
avg_temperature     0
max_temperature     0
avg_systolic_bp     0
avg_diastolic_bp    0
vital_readings      0
dtype: int64

In [ ]:
# Aggregate treatment information at admission level

treatments_agg = (
    treatments.groupby('admission_id')
    .agg(
        treatment_count=('treatment_id', 'count'),
        procedure_count=('procedure', 'nunique'),
        medication_count=('medication', 'nunique')
    )
    .reset_index()
)

print("=" * 70)
print("TREATMENT AGGREGATION")
print("=" * 70)

print("\nAggregated shape:", treatments_agg.shape)

print("\nSample:")
print(treatments_agg.head())

print("\nMissing values:")
print(treatments_agg.isnull().sum())

======================================================================
TREATMENT AGGREGATION
======================================================================

Aggregated shape: (3324, 4)

Sample:
   admission_id  treatment_count  procedure_count  medication_count
0          2001                4                1                 1
1          2002                1                1                 1
2          2003                4                1                 1
3          2004                2                1                 1
4          2005                2                1                 1

Missing values:
admission_id        0
treatment_count     0
procedure_count     0
medication_count    0
dtype: int64

In [ ]:
# Create the admission-level analytics dataset

analytics_df = (
    admissions
    .merge(
        patients[
            ['patient_id', 'age', 'gender',
             'chronic_conditions', 'has_chronic_condition']
        ],
        on='patient_id',
        how='left'
    )
    .merge(
        vitals_agg,
        on='admission_id',
        how='left'
    )
    .merge(
        treatments_agg,
        on='admission_id',
        how='left'
    )
)

print("=" * 70)
print("ADMISSION-LEVEL ANALYTICS DATASET")
print("=" * 70)

print("\nShape:", analytics_df.shape)

print("\nMissing values:")
print(analytics_df.isnull().sum())

print("\nSample:")
print(analytics_df.head())

======================================================================
ADMISSION-LEVEL ANALYTICS DATASET
======================================================================

Shape: (3324, 26)

Missing values:
admission_id             0
patient_id               0
admission_date           0
discharge_date           0
diagnosis                0
doctor_id                0
room_no                  0
length_of_stay           0
previous_admissions      0
age                      0
gender                   0
chronic_conditions       0
has_chronic_condition    0
avg_heart_rate           0
min_heart_rate           0
max_heart_rate           0
avg_oxygen_level         0
min_oxygen_level         0
avg_temperature          0
max_temperature          0
avg_systolic_bp          0
avg_diastolic_bp         0
vital_readings           0
treatment_count          0
procedure_count          0
medication_count         0
dtype: int64

Sample:
   admission_id  patient_id admission_date discharge_date  \
0          2001        1001     2026-02-07     2026-02-13
1          2002        1001     2026-03-07     2026-03-17
2          2003        1002     2025-05-16     2025-05-21
3          2005        1003     2025-08-11     2025-08-21
4          2004        1003     2025-12-08     2025-12-10

               diagnosis  doctor_id room_no  length_of_stay  \
0  Diabetes Complication        317    R418               6
1          Heart Failure        320    R396              10
2          Asthma Attack        339    R411               5
3              Pneumonia        306    R368              10
4  Respiratory Infection        325    R120               2

   previous_admissions  age  gender     chronic_conditions  \
0                    0   49  Female               Diabetes
1                    1   49  Female               Diabetes
2                    0   61  Female                 Asthma
3                    0   86  Female  No Recorded Condition
4                    1   86  Female  No Recorded Condition

   has_chronic_condition  avg_heart_rate  min_heart_rate  max_heart_rate  \
0                      1       91.000000              65             120
1                      1       90.916667              67             117
2                      1       83.866667              61             118
3                      0       90.400000              66             114
4                      0       83.777778              60             114

   avg_oxygen_level  min_oxygen_level  avg_temperature  max_temperature  \
0         93.888889                88        99.253333           100.48
1         92.666667                88        99.038333           100.85
2         94.200000                88        98.618667           100.41
3         95.000000                89        99.197000           100.86
4         92.222222                88        98.910000           100.60

   avg_systolic_bp  avg_diastolic_bp  vital_readings  treatment_count  \
0       129.444444         83.000000               9                4
1       119.916667         84.583333              12                1
2       133.333333         82.133333              15                4
3       134.100000         81.500000              10                2
4       139.555556         79.555556               9                2

   procedure_count  medication_count
0                1                 1
1                1                 1
2                1                 1
3                1                 1
4                1                 1

In [ ]:
# Numerical feature summary

numeric_columns = [
    'age',
    'length_of_stay',
    'previous_admissions',
    'avg_heart_rate',
    'avg_oxygen_level',
    'avg_temperature',
    'avg_systolic_bp',
    'avg_diastolic_bp',
    'vital_readings',
    'treatment_count'
]

print("=" * 70)
print("NUMERICAL FEATURE SUMMARY")
print("=" * 70)

display(
    analytics_df[numeric_columns]
    .describe()
    .round(2)
)

======================================================================
NUMERICAL FEATURE SUMMARY
======================================================================

,age,length_of_stay,previous_admissions,avg_heart_rate,avg_oxygen_level,avg_temperature,avg_systolic_bp,avg_diastolic_bp,vital_readings,treatment_count
count,3324.00,3324.00,3324.00,3324.00,3324.00,3324.00,3324.00,3324.00,3324.00,3324.00
mean,54.80,5.97,0.65,89.86,93.98,99.01,130.11,82.45,9.97,2.51
std,21.18,2.58,0.74,5.98,1.25,0.39,3.94,2.58,3.17,1.12
min,18.00,2.00,0.00,65.33,89.00,97.58,116.25,72.67,5.00,1.00
25%,36.00,4.00,0.00,86.00,93.15,98.74,127.56,80.82,7.00,2.00
50%,56.00,6.00,0.00,90.00,94.00,99.01,130.14,82.42,10.00,3.00
75%,73.00,8.00,1.00,93.83,94.80,99.27,132.77,84.15,13.00,4.00
max,90.00,10.00,2.00,113.40,98.00,100.40,144.17,91.29,15.00,4.00

In [ ]:
# Admission distribution by diagnosis

diagnosis_counts = (
    analytics_df['diagnosis']
    .value_counts()
    .reset_index()
)

diagnosis_counts.columns = ['diagnosis', 'admission_count']

print("=" * 70)
print("ADMISSIONS BY DIAGNOSIS")
print("=" * 70)

display(diagnosis_counts)

print("\nTotal Admissions:", diagnosis_counts['admission_count'].sum())

======================================================================
ADMISSIONS BY DIAGNOSIS
======================================================================

               diagnosis  admission_count
0           Hypertension              746
1  Respiratory Infection              689
2             Chest Pain              485
3          Heart Failure              473
4              Pneumonia              454
5          Asthma Attack              252
6  Diabetes Complication              225

Total Admissions: 3324

In [ ]:
# Monthly admission trend

analytics_df['admission_month'] = (
    analytics_df['admission_date']
    .dt.to_period('M')
    .astype(str)
)

monthly_admissions = (
    analytics_df['admission_month']
    .value_counts()
    .sort_index()
    .reset_index()
)

monthly_admissions.columns = ['admission_month', 'admission_count']

print("=" * 70)
print("MONTHLY ADMISSION TREND")
print("=" * 70)

display(monthly_admissions)

print("\nTotal Admissions:", monthly_admissions['admission_count'].sum())

======================================================================
MONTHLY ADMISSION TREND
======================================================================

   admission_month  admission_count
0          2025-03              169
1          2025-04              270
2          2025-05              275
3          2025-06              265
4          2025-07              277
5          2025-08              278
6          2025-09              269
7          2025-10              285
8          2025-11              300
9          2025-12              262
10         2026-01              274
11         2026-02              259
12         2026-03              141

Total Admissions: 3324

In [ ]:
# Admission distribution by gender

gender_admissions = (
    analytics_df['gender']
    .value_counts()
    .reset_index()
)

gender_admissions.columns = ['gender', 'admission_count']

print("=" * 70)
print("ADMISSIONS BY GENDER")
print("=" * 70)

display(gender_admissions)

print("\nTotal Admissions:", gender_admissions['admission_count'].sum())

======================================================================
ADMISSIONS BY GENDER
======================================================================

   gender  admission_count
0  Female             1758
1    Male             1566

Total Admissions: 3324

In [ ]:
# Admissions by chronic condition

chronic_admissions = (
    analytics_df['chronic_conditions']
    .value_counts()
    .reset_index()
)

chronic_admissions.columns = ['chronic_condition', 'admission_count']

print("=" * 70)
print("ADMISSIONS BY CHRONIC CONDITION")
print("=" * 70)

display(chronic_admissions)

print("\nTotal Admissions:", chronic_admissions['admission_count'].sum())

======================================================================
ADMISSIONS BY CHRONIC CONDITION
======================================================================

       chronic_condition  admission_count
0          Heart Disease              511
1         Kidney Disease              503
2                 Asthma              490
3           Hypertension              462
4  No Recorded Condition              462
5               Diabetes              453
6                   COPD              443

Total Admissions: 3324

In [ ]:
# Average length of stay by diagnosis

los_by_diagnosis = (
    analytics_df.groupby('diagnosis')['length_of_stay']
    .agg(['count', 'mean', 'min', 'max'])
    .round(2)
    .reset_index()
    .sort_values('mean', ascending=False)
)

print("=" * 70)
print("LENGTH OF STAY BY DIAGNOSIS")
print("=" * 70)

display(los_by_diagnosis)

======================================================================
LENGTH OF STAY BY DIAGNOSIS
======================================================================

               diagnosis  count  mean  min  max
1             Chest Pain    485  6.09    2   10
6  Respiratory Infection    689  6.06    2   10
4           Hypertension    746  6.05    2   10
3          Heart Failure    473  5.88    2   10
5              Pneumonia    454  5.84    2   10
2  Diabetes Complication    225  5.80    2   10
0          Asthma Attack    252  5.77    2   10

In [ ]:
# Analyze whether previous admissions are associated with length of stay

previous_admission_los = (
    analytics_df.groupby('previous_admissions')['length_of_stay']
    .agg(['count', 'mean', 'min', 'max'])
    .round(2)
    .reset_index()
)

print("=" * 70)
print("PREVIOUS ADMISSIONS VS LENGTH OF STAY")
print("=" * 70)

display(previous_admission_los)

======================================================================
PREVIOUS ADMISSIONS VS LENGTH OF STAY
======================================================================

   previous_admissions  count  mean  min  max
0                    0   1690  5.95    2   10
1                    1   1108  6.11    2   10
2                    2    526  5.73    2   10

In [ ]:
# Vital sign patterns by diagnosis

vitals_by_diagnosis = (
    analytics_df.groupby('diagnosis')
    .agg(
        avg_heart_rate=('avg_heart_rate', 'mean'),
        avg_oxygen_level=('avg_oxygen_level', 'mean'),
        avg_temperature=('avg_temperature', 'mean'),
        avg_systolic_bp=('avg_systolic_bp', 'mean'),
        avg_diastolic_bp=('avg_diastolic_bp', 'mean')
    )
    .round(2)
    .reset_index()
    .sort_values('avg_heart_rate', ascending=False)
)

print("=" * 70)
print("VITAL SIGN SUMMARY BY DIAGNOSIS")
print("=" * 70)

display(vitals_by_diagnosis)

======================================================================
VITAL SIGN SUMMARY BY DIAGNOSIS
======================================================================

,diagnosis,avg_heart_rate,avg_oxygen_level,avg_temperature,avg_systolic_bp,avg_diastolic_bp
2,Diabetes Complication,90.47,94.03,99.03,129.87,82.48
4,Hypertension,90.30,93.97,99.01,130.20,82.39
6,Respiratory Infection,89.89,93.97,99.01,130.32,82.29
3,Heart Failure,89.81,94.00,98.98,130.04,82.39
5,Pneumonia,89.62,93.96,99.00,130.19,82.77
1,Chest Pain,89.41,93.94,99.02,129.84,82.48
0,Asthma Attack,89.38,93.99,99.01,130.02,82.47

In [ ]:
# Treatment patterns by diagnosis

treatment_by_diagnosis = (
    analytics_df.groupby('diagnosis')
    .agg(
        admission_count=('admission_id', 'count'),
        avg_treatment_count=('treatment_count', 'mean'),
        avg_procedure_count=('procedure_count', 'mean'),
        avg_medication_count=('medication_count', 'mean')
    )
    .round(2)
    .reset_index()
    .sort_values('avg_treatment_count', ascending=False)
)

print("=" * 70)
print("TREATMENT ANALYSIS BY DIAGNOSIS")
print("=" * 70)

display(treatment_by_diagnosis)

======================================================================
TREATMENT ANALYSIS BY DIAGNOSIS
======================================================================

,diagnosis,admission_count,avg_treatment_count,avg_procedure_count,avg_medication_count
6,Respiratory Infection,689,2.57,1.0,1.0
3,Heart Failure,473,2.56,1.0,1.0
4,Hypertension,746,2.51,1.0,1.0
5,Pneumonia,454,2.49,1.0,1.0
0,Asthma Attack,252,2.45,1.0,1.0
2,Diabetes Complication,225,2.43,1.0,1.0
1,Chest Pain,485,2.43,1.0,1.0

In [ ]:
# Identify admissions with potentially concerning average vital signs

analytics_df['vital_risk_flags'] = (
    (analytics_df['avg_heart_rate'] > 100) |
    (analytics_df['avg_oxygen_level'] < 92) |
    (analytics_df['avg_temperature'] > 100) |
    (analytics_df['avg_systolic_bp'] > 140) |
    (analytics_df['avg_diastolic_bp'] > 90)
).astype(int)

vital_risk_summary = (
    analytics_df['vital_risk_flags']
    .value_counts()
    .rename(index={0: 'No Flag', 1: 'Potential Risk Flag'})
    .reset_index()
)

vital_risk_summary.columns = ['vital_status', 'admission_count']

print("=" * 70)
print("POTENTIAL VITAL SIGN RISK FLAGS")
print("=" * 70)

display(vital_risk_summary)

print("\nTotal Admissions:", vital_risk_summary['admission_count'].sum())

======================================================================
POTENTIAL VITAL SIGN RISK FLAGS
======================================================================

          vital_status  admission_count
0              No Flag             2977
1  Potential Risk Flag              347

Total Admissions: 3324

In [ ]:
# Potential vital-sign risk flags by diagnosis

risk_by_diagnosis = (
    analytics_df.groupby('diagnosis')
    .agg(
        admission_count=('admission_id', 'count'),
        risk_flag_count=('vital_risk_flags', 'sum')
    )
    .reset_index()
)

risk_by_diagnosis['risk_flag_percentage'] = (
    risk_by_diagnosis['risk_flag_count']
    / risk_by_diagnosis['admission_count'] * 100
).round(2)

risk_by_diagnosis = risk_by_diagnosis.sort_values(
    'risk_flag_percentage',
    ascending=False
)

print("=" * 70)
print("POTENTIAL VITAL RISK FLAGS BY DIAGNOSIS")
print("=" * 70)

display(risk_by_diagnosis)

======================================================================
POTENTIAL VITAL RISK FLAGS BY DIAGNOSIS
======================================================================

,diagnosis,admission_count,risk_flag_count,risk_flag_percentage
5,Pneumonia,454,56,12.33
1,Chest Pain,485,56,11.55
4,Hypertension,746,78,10.46
6,Respiratory Infection,689,69,10.01
2,Diabetes Complication,225,22,9.78
3,Heart Failure,473,44,9.30
0,Asthma Attack,252,22,8.73

In [ ]:
# Create age groups and analyze admissions

analytics_df['age_group'] = pd.cut(
    analytics_df['age'],
    bins=[0, 30, 45, 60, 75, 120],
    labels=['18-30', '31-45', '46-60', '61-75', '76+'],
    right=True
)

age_group_analysis = (
    analytics_df.groupby('age_group', observed=False)
    .agg(
        admission_count=('admission_id', 'count'),
        avg_length_of_stay=('length_of_stay', 'mean'),
        risk_flag_count=('vital_risk_flags', 'sum')
    )
    .round(2)
    .reset_index()
)

age_group_analysis['risk_flag_percentage'] = (
    age_group_analysis['risk_flag_count']
    / age_group_analysis['admission_count'] * 100
).round(2)

print("=" * 70)
print("AGE GROUP ANALYSIS")
print("=" * 70)

display(age_group_analysis)

======================================================================
AGE GROUP ANALYSIS
======================================================================

,age_group,admission_count,avg_length_of_stay,risk_flag_count,risk_flag_percentage
0,18-30,584,5.88,67,11.47
1,31-45,649,5.99,73,11.25
2,46-60,643,5.83,62,9.64
3,61-75,727,6.08,84,11.55
4,76+,721,6.02,61,8.46

In [ ]:
# Compare potential vital risk flags for patients with and without chronic conditions

chronic_risk_analysis = (
    analytics_df.groupby('has_chronic_condition')
    .agg(
        admission_count=('admission_id', 'count'),
        risk_flag_count=('vital_risk_flags', 'sum'),
        avg_length_of_stay=('length_of_stay', 'mean')
    )
    .round(2)
    .reset_index()
)

chronic_risk_analysis['risk_flag_percentage'] = (
    chronic_risk_analysis['risk_flag_count']
    / chronic_risk_analysis['admission_count'] * 100
).round(2)

chronic_risk_analysis['chronic_status'] = chronic_risk_analysis[
    'has_chronic_condition'
].map({
    0: 'No Recorded Condition',
    1: 'Has Chronic Condition'
})

chronic_risk_analysis = chronic_risk_analysis[
    ['chronic_status', 'admission_count', 'risk_flag_count',
     'risk_flag_percentage', 'avg_length_of_stay']
]

print("=" * 70)
print("CHRONIC CONDITION VS VITAL RISK")
print("=" * 70)

display(chronic_risk_analysis)

======================================================================
CHRONIC CONDITION VS VITAL RISK
======================================================================

,chronic_status,admission_count,risk_flag_count,risk_flag_percentage,avg_length_of_stay
0,No Recorded Condition,462,54,11.69,5.86
1,Has Chronic Condition,2862,293,10.24,5.98

In [ ]:
# Analyze admissions handled by each doctor

doctor_workload = (
    analytics_df.groupby('doctor_id')
    .agg(
        admission_count=('admission_id', 'count'),
        avg_length_of_stay=('length_of_stay', 'mean'),
        risk_flag_count=('vital_risk_flags', 'sum')
    )
    .round(2)
    .reset_index()
    .sort_values('admission_count', ascending=False)
)

print("=" * 70)
print("DOCTOR WORKLOAD ANALYSIS")
print("=" * 70)

display(doctor_workload)

======================================================================
DOCTOR WORKLOAD ANALYSIS
======================================================================

    doctor_id  admission_count  avg_length_of_stay  risk_flag_count
6         310              209                6.08               18
17        321              201                6.01               20
1         302              196                6.19               19
26        339              189                5.79               26
4         307              185                5.85               20
0         301              182                5.79               16
25        337              180                6.02               22
3         306              171                5.87               19
20        325              170                5.75               11
12        316              159                6.01               18
10        314              151                6.30               20
18        322              148                6.09               16
5         309               99                6.05                7
9         313               97                6.09               15
24        333               96                5.74                9
16        320               94                6.33               12
2         303               91                5.51                8
19        324               90                6.41               11
27        340               89                6.06               11
22        329               79                5.99               10
15        319               77                6.10                6
23        332               75                5.64                8
7         311               71                5.83                3
11        315               55                5.89                6
8         312               44                5.93                5
14        318               43                6.00                5
21        328               43                5.47                4
13        317               40                5.70                2

In [ ]:
# Create a combined admission risk profile
# This is an analytical screening score, not a clinical diagnosis.

analytics_df['risk_factor_count'] = (
    analytics_df['vital_risk_flags']
    + analytics_df['has_chronic_condition']
    + (analytics_df['previous_admissions'] > 0).astype(int)
)

risk_profile = (
    analytics_df.groupby('risk_factor_count')
    .agg(
        admission_count=('admission_id', 'count'),
        avg_length_of_stay=('length_of_stay', 'mean')
    )
    .round(2)
    .reset_index()
)

print("=" * 70)
print("ADMISSION RISK PROFILE")
print("=" * 70)

display(risk_profile)

print("\nTotal Admissions:", risk_profile['admission_count'].sum())

======================================================================
ADMISSION RISK PROFILE
======================================================================

   risk_factor_count  admission_count  avg_length_of_stay
0                  0              211                5.89
1                  1             1534                5.99
2                  2             1428                5.93
3                  3              151                6.25

Total Admissions: 3324

In [ ]:
# Prepare admission-level dataset for predictive analysis

model_df = analytics_df[
    [
        'admission_id',
        'age',
        'gender',
        'has_chronic_condition',
        'previous_admissions',
        'length_of_stay',
        'avg_heart_rate',
        'avg_oxygen_level',
        'avg_temperature',
        'avg_systolic_bp',
        'avg_diastolic_bp',
        'treatment_count',
        'procedure_count',
        'medication_count',
        'vital_risk_flags'
    ]
].copy()

print("=" * 70)
print("PREDICTIVE MODELING DATASET")
print("=" * 70)

print("Shape:", model_df.shape)
print("\nMissing values:")
display(model_df.isnull().sum())

print("\nPreview:")
display(model_df.head())

======================================================================
PREDICTIVE MODELING DATASET
======================================================================
Shape: (3324, 15)

Missing values:

admission_id             0
age                      0
gender                   0
has_chronic_condition    0
previous_admissions      0
length_of_stay           0
avg_heart_rate           0
avg_oxygen_level         0
avg_temperature          0
avg_systolic_bp          0
avg_diastolic_bp         0
treatment_count          0
procedure_count          0
medication_count         0
vital_risk_flags         0
dtype: int64

Preview:

,admission_id,age,gender,has_chronic_condition,previous_admissions,length_of_stay,avg_heart_rate,avg_oxygen_level,avg_temperature,avg_systolic_bp,avg_diastolic_bp,treatment_count,procedure_count,medication_count,vital_risk_flags
0,2001,49,Female,1,0,6,91.000000,93.888889,99.253333,129.444444,83.000000,4,1,1,0
1,2002,49,Female,1,1,10,90.916667,92.666667,99.038333,119.916667,84.583333,1,1,1,0
2,2003,61,Female,1,0,5,83.866667,94.200000,98.618667,133.333333,82.133333,4,1,1,0
3,2005,86,Female,0,0,10,90.400000,95.000000,99.197000,134.100000,81.500000,2,1,1,0
4,2004,86,Female,0,1,2,83.777778,92.222222,98.910000,139.555556,79.555556,2,1,1,0

In [ ]:
# Check whether an actual readmission target is available

possible_target_columns = [
    col for col in analytics_df.columns
    if any(keyword in col.lower() for keyword in ['readmission', 'readmit', 'risk_level', 'risk_score'])
]

print("=" * 70)
print("READMISSION TARGET AVAILABILITY CHECK")
print("=" * 70)

if possible_target_columns:
    print("Potential target columns found:")
    print(possible_target_columns)
else:
    print("No actual readmission/risk target column is available in the supplied datasets.")

print("\nAvailable analytics columns:")
print(analytics_df.columns.tolist())

======================================================================
READMISSION TARGET AVAILABILITY CHECK
======================================================================
No actual readmission/risk target column is available in the supplied datasets.

Available analytics columns:
['admission_id', 'patient_id', 'admission_date', 'discharge_date', 'diagnosis', 'doctor_id', 'room_no', 'length_of_stay', 'previous_admissions', 'age', 'gender', 'chronic_conditions', 'has_chronic_condition', 'avg_heart_rate', 'min_heart_rate', 'max_heart_rate', 'avg_oxygen_level', 'min_oxygen_level', 'avg_temperature', 'max_temperature', 'avg_systolic_bp', 'avg_diastolic_bp', 'vital_readings', 'treatment_count', 'procedure_count', 'medication_count', 'admission_month', 'vital_risk_flags', 'age_group', 'risk_factor_count']

In [ ]:
# Create a project-defined analytical risk score
# This is NOT a clinical diagnosis or an observed readmission outcome.

risk_score_df = analytics_df[
    [
        'admission_id',
        'age',
        'previous_admissions',
        'has_chronic_condition',
        'vital_risk_flags',
        'length_of_stay',
        'avg_oxygen_level',
        'avg_heart_rate'
    ]
].copy()

# Assign points to selected risk indicators
risk_score_df['age_points'] = pd.cut(
    risk_score_df['age'],
    bins=[0, 45, 60, 75, 120],
    labels=[0, 1, 2, 3],
    include_lowest=True
).astype(int)

risk_score_df['previous_admission_points'] = (
    risk_score_df['previous_admissions'].clip(upper=2)
)

risk_score_df['chronic_condition_points'] = (
    risk_score_df['has_chronic_condition']
)

risk_score_df['vital_risk_points'] = (
    risk_score_df['vital_risk_flags']
)

risk_score_df['risk_score'] = (
    risk_score_df['age_points']
    + risk_score_df['previous_admission_points']
    + risk_score_df['chronic_condition_points']
    + risk_score_df['vital_risk_points']
)

print("=" * 70)
print("ANALYTICAL RISK SCORE")
print("=" * 70)

print("Score range:",
      risk_score_df['risk_score'].min(),
      "to",
      risk_score_df['risk_score'].max())

display(
    risk_score_df[
        ['admission_id', 'age', 'previous_admissions',
         'has_chronic_condition', 'vital_risk_flags',
         'risk_score']
    ].head(10)
)

======================================================================
ANALYTICAL RISK SCORE
======================================================================
Score range: 0 to 7

,admission_id,age,previous_admissions,has_chronic_condition,vital_risk_flags,risk_score
0,2001,49,0,1,0,2
1,2002,49,1,1,0,3
2,2003,61,0,1,0,3
3,2005,86,0,0,0,3
4,2004,86,1,0,0,4
5,2006,78,0,0,0,3
6,2007,78,1,0,0,4
7,2008,78,2,0,0,5
8,2009,78,0,1,0,4
9,2010,38,0,0,0,0

In [ ]:
# Categorize the analytical risk score into Low, Medium, and High levels

risk_score_df['risk_level'] = pd.cut(
    risk_score_df['risk_score'],
    bins=[-1, 2, 4, 7],
    labels=['Low', 'Medium', 'High']
)

print("=" * 70)
print("ANALYTICAL RISK LEVEL DISTRIBUTION")
print("=" * 70)

print(risk_score_df['risk_level'].value_counts().sort_index())

print("\nRisk level percentages:")
print(
    (risk_score_df['risk_level'].value_counts(normalize=True).sort_index() * 100)
    .round(2)
)

======================================================================
ANALYTICAL RISK LEVEL DISTRIBUTION
======================================================================
risk_level
Low       1400
Medium    1443
High       481
Name: count, dtype: int64

Risk level percentages:
risk_level
Low       42.12
Medium    43.41
High      14.47
Name: proportion, dtype: float64

In [ ]:
# Add analytical risk score and risk level to the main analytics dataset

analytics_df = analytics_df.merge(
    risk_score_df[
        ['admission_id', 'risk_score', 'risk_level']
    ],
    on='admission_id',
    how='left'
)

print("=" * 70)
print("FINAL ANALYTICS DATASET")
print("=" * 70)

print("\nShape:", analytics_df.shape)

print("\nMissing values in risk fields:")
print(
    analytics_df[
        ['risk_score', 'risk_level']
    ].isnull().sum()
)

print("\nRisk Level Distribution:")
print(
    analytics_df['risk_level']
    .value_counts()
    .sort_index()
)

print("\nFinal columns:")
print(analytics_df.columns.tolist())

======================================================================
FINAL ANALYTICS DATASET
======================================================================

Shape: (3324, 32)

Missing values in risk fields:
risk_score    0
risk_level    0
dtype: int64

Risk Level Distribution:
risk_level
Low       1400
Medium    1443
High       481
Name: count, dtype: int64

Final columns:
['admission_id', 'patient_id', 'admission_date', 'discharge_date', 'diagnosis', 'doctor_id', 'room_no', 'length_of_stay', 'previous_admissions', 'age', 'gender', 'chronic_conditions', 'has_chronic_condition', 'avg_heart_rate', 'min_heart_rate', 'max_heart_rate', 'avg_oxygen_level', 'min_oxygen_level', 'avg_temperature', 'max_temperature', 'avg_systolic_bp', 'avg_diastolic_bp', 'vital_readings', 'treatment_count', 'procedure_count', 'medication_count', 'admission_month', 'vital_risk_flags', 'age_group', 'risk_factor_count', 'risk_score', 'risk_level']

In [ ]:
# Final data quality validation before MySQL export

print("=" * 70)
print("FINAL DATA QUALITY CHECK")
print("=" * 70)

print("\n1. Dataset shape:")
print(analytics_df.shape)

print("\n2. Duplicate admission IDs:")
print(analytics_df['admission_id'].duplicated().sum())

print("\n3. Missing values:")
print("Total missing values:", analytics_df.isnull().sum().sum())

print("\n4. Risk score range:")
print(
    analytics_df['risk_score'].min(),
    "to",
    analytics_df['risk_score'].max()
)

print("\n5. Risk level counts:")
print(analytics_df['risk_level'].value_counts().sort_index())

print("\n6. Admission date range:")
print(
    analytics_df['admission_date'].min(),
    "to",
    analytics_df['admission_date'].max()
)

print("\n7. Patient IDs without matching patient records:")
print(
    (~analytics_df['patient_id'].isin(patients['patient_id'])).sum()
)

print("\n8. Doctor IDs without matching doctor records:")
print(
    (~analytics_df['doctor_id'].isin(doctors['doctor_id'])).sum()
)

print("\nFinal validation completed.")

======================================================================
FINAL DATA QUALITY CHECK
======================================================================

1. Dataset shape:
(3324, 32)

2. Duplicate admission IDs:
0

3. Missing values:
Total missing values: 0

4. Risk score range:
0 to 7

5. Risk level counts:
risk_level
Low       1400
Medium    1443
High       481
Name: count, dtype: int64

6. Admission date range:
2025-03-11 00:00:00 to 2026-03-11 00:00:00

7. Patient IDs without matching patient records:
0

8. Doctor IDs without matching doctor records:
0

Final validation completed.

In [ ]:
# Export cleaned datasets for MySQL loading

export_files = {
    'patients_clean.csv': patients,
    'doctors_clean.csv': doctors,
    'admissions_clean.csv': admissions,
    'treatments_clean.csv': treatments,
    'vitals_clean.csv': vitals,
    'healthcare_analytics.csv': analytics_df
}

print("=" * 70)
print("EXPORTING CLEANED DATASETS")
print("=" * 70)

for filename, dataframe in export_files.items():
    path = f'/content/{filename}'
    dataframe.to_csv(path, index=False)
    print(f"{filename:<30} {dataframe.shape}")

print("\nAll cleaned datasets exported successfully.")

======================================================================
EXPORTING CLEANED DATASETS
======================================================================
patients_clean.csv             (1690, 10)
doctors_clean.csv              (40, 5)
admissions_clean.csv           (3324, 9)
treatments_clean.csv           (8329, 6)
vitals_clean.csv               (33148, 9)
healthcare_analytics.csv       (3324, 32)

All cleaned datasets exported successfully.

In [ ]:
print("Original DimEmployee rows:", len(DimEmployee))
print("\nEmployee keys:")
print(sorted(DimEmployee["EmployeeKey"].tolist()))

NameError: name 'DimEmployee' is not defined